//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace AssortingKanban.ForAssortingKanban {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IForAssortingKanbanService", Namespace="http://tempuri.org/")]
    public partial class ForAssortingKanbanService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback QueryChannelsOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryTodayStatisticsOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryCurrentTaskInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryPDATodayStatisticsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ForAssortingKanbanService() {
            this.Url = global::AssortingKanban.Properties.Settings.Default.分拣看板_ForAssortingKanban_ForAssortingKanbanService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event QueryChannelsCompletedEventHandler QueryChannelsCompleted;
        
        /// <remarks/>
        public event QueryTodayStatisticsCompletedEventHandler QueryTodayStatisticsCompleted;
        
        /// <remarks/>
        public event QueryCurrentTaskInfoCompletedEventHandler QueryCurrentTaskInfoCompleted;
        
        /// <remarks/>
        public event QueryPDATodayStatisticsCompletedEventHandler QueryPDATodayStatisticsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IForAssortingKanbanService/QueryChannels", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CFG_ChannelDto[] QueryChannels() {
            object[] results = this.Invoke("QueryChannels", new object[0]);
            return ((CFG_ChannelDto[])(results[0]));
        }
        
        /// <remarks/>
        public void QueryChannelsAsync() {
            this.QueryChannelsAsync(null);
        }
        
        /// <remarks/>
        public void QueryChannelsAsync(object userState) {
            if ((this.QueryChannelsOperationCompleted == null)) {
                this.QueryChannelsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryChannelsOperationCompleted);
            }
            this.InvokeAsync("QueryChannels", new object[0], this.QueryChannelsOperationCompleted, userState);
        }
        
        private void OnQueryChannelsOperationCompleted(object arg) {
            if ((this.QueryChannelsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryChannelsCompleted(this, new QueryChannelsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IForAssortingKanbanService/QueryTodayStatistics", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AssortingKanbanTodayStatistics QueryTodayStatistics(int cfgChannelId) {
            object[] results = this.Invoke("QueryTodayStatistics", new object[] {
                        cfgChannelId});
            return ((AssortingKanbanTodayStatistics)(results[0]));
        }
        
        /// <remarks/>
        public void QueryTodayStatisticsAsync(int cfgChannelId) {
            this.QueryTodayStatisticsAsync(cfgChannelId, null);
        }
        
        /// <remarks/>
        public void QueryTodayStatisticsAsync(int cfgChannelId, object userState) {
            if ((this.QueryTodayStatisticsOperationCompleted == null)) {
                this.QueryTodayStatisticsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryTodayStatisticsOperationCompleted);
            }
            this.InvokeAsync("QueryTodayStatistics", new object[] {
                        cfgChannelId}, this.QueryTodayStatisticsOperationCompleted, userState);
        }
        
        private void OnQueryTodayStatisticsOperationCompleted(object arg) {
            if ((this.QueryTodayStatisticsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryTodayStatisticsCompleted(this, new QueryTodayStatisticsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IForAssortingKanbanService/QueryCurrentTaskInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AssortingKanbanTaskInfo QueryCurrentTaskInfo(int cfgChannelId) {
            object[] results = this.Invoke("QueryCurrentTaskInfo", new object[] {
                        cfgChannelId});
            return ((AssortingKanbanTaskInfo)(results[0]));
        }
        
        /// <remarks/>
        public void QueryCurrentTaskInfoAsync(int cfgChannelId) {
            this.QueryCurrentTaskInfoAsync(cfgChannelId, null);
        }
        
        /// <remarks/>
        public void QueryCurrentTaskInfoAsync(int cfgChannelId, object userState) {
            if ((this.QueryCurrentTaskInfoOperationCompleted == null)) {
                this.QueryCurrentTaskInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryCurrentTaskInfoOperationCompleted);
            }
            this.InvokeAsync("QueryCurrentTaskInfo", new object[] {
                        cfgChannelId}, this.QueryCurrentTaskInfoOperationCompleted, userState);
        }
        
        private void OnQueryCurrentTaskInfoOperationCompleted(object arg) {
            if ((this.QueryCurrentTaskInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryCurrentTaskInfoCompleted(this, new QueryCurrentTaskInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IForAssortingKanbanService/QueryPDATodayStatistics", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AssortingKanbanTodayStatistics QueryPDATodayStatistics(int cfgChannelId) {
            object[] results = this.Invoke("QueryPDATodayStatistics", new object[] {
                        cfgChannelId});
            return ((AssortingKanbanTodayStatistics)(results[0]));
        }
        
        /// <remarks/>
        public void QueryPDATodayStatisticsAsync(int cfgChannelId) {
            this.QueryPDATodayStatisticsAsync(cfgChannelId, null);
        }
        
        /// <remarks/>
        public void QueryPDATodayStatisticsAsync(int cfgChannelId, object userState) {
            if ((this.QueryPDATodayStatisticsOperationCompleted == null)) {
                this.QueryPDATodayStatisticsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryPDATodayStatisticsOperationCompleted);
            }
            this.InvokeAsync("QueryPDATodayStatistics", new object[] {
                        cfgChannelId}, this.QueryPDATodayStatisticsOperationCompleted, userState);
        }
        
        private void OnQueryPDATodayStatisticsOperationCompleted(object arg) {
            if ((this.QueryPDATodayStatisticsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryPDATodayStatisticsCompleted(this, new QueryPDATodayStatisticsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CFG_ChannelDto {
        
        private int idField;
        
        private string codeField;
        
        private string nameField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AST_CartTaskItemDto {
        
        private long aST_CartTaskItemIdField;
        
        private int cartPositionField;
        
        private string workStationCodeField;
        
        private string materialCodeField;
        
        private string materialNameField;
        
        private string materialBarcodeField;
        
        private int maxQuantityInSingleCartPositionField;
        
        private bool isSpecialField;
        
        private bool isBigField;
        
        private AssortingStatus assortingStatusField;
        
        private System.Nullable<int> pickedQuantityField;
        
        /// <remarks/>
        public long AST_CartTaskItemId {
            get {
                return this.aST_CartTaskItemIdField;
            }
            set {
                this.aST_CartTaskItemIdField = value;
            }
        }
        
        /// <remarks/>
        public int CartPosition {
            get {
                return this.cartPositionField;
            }
            set {
                this.cartPositionField = value;
            }
        }
        
        /// <remarks/>
        public string WorkStationCode {
            get {
                return this.workStationCodeField;
            }
            set {
                this.workStationCodeField = value;
            }
        }
        
        /// <remarks/>
        public string MaterialCode {
            get {
                return this.materialCodeField;
            }
            set {
                this.materialCodeField = value;
            }
        }
        
        /// <remarks/>
        public string MaterialName {
            get {
                return this.materialNameField;
            }
            set {
                this.materialNameField = value;
            }
        }
        
        /// <remarks/>
        public string MaterialBarcode {
            get {
                return this.materialBarcodeField;
            }
            set {
                this.materialBarcodeField = value;
            }
        }
        
        /// <remarks/>
        public int MaxQuantityInSingleCartPosition {
            get {
                return this.maxQuantityInSingleCartPositionField;
            }
            set {
                this.maxQuantityInSingleCartPositionField = value;
            }
        }
        
        /// <remarks/>
        public bool IsSpecial {
            get {
                return this.isSpecialField;
            }
            set {
                this.isSpecialField = value;
            }
        }
        
        /// <remarks/>
        public bool IsBig {
            get {
                return this.isBigField;
            }
            set {
                this.isBigField = value;
            }
        }
        
        /// <remarks/>
        public AssortingStatus AssortingStatus {
            get {
                return this.assortingStatusField;
            }
            set {
                this.assortingStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> PickedQuantity {
            get {
                return this.pickedQuantityField;
            }
            set {
                this.pickedQuantityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum AssortingStatus {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Assorting,
        
        /// <remarks/>
        WaitingConfirm,
        
        /// <remarks/>
        Finished,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AST_CartTaskDto {
        
        private long aST_CartTaskIdField;
        
        private int cFG_CartIdField;
        
        private string cartCodeField;
        
        private string cartNameField;
        
        private AST_CartTaskItemDto[] itemsField;
        
        /// <remarks/>
        public long AST_CartTaskId {
            get {
                return this.aST_CartTaskIdField;
            }
            set {
                this.aST_CartTaskIdField = value;
            }
        }
        
        /// <remarks/>
        public int CFG_CartId {
            get {
                return this.cFG_CartIdField;
            }
            set {
                this.cFG_CartIdField = value;
            }
        }
        
        /// <remarks/>
        public string CartCode {
            get {
                return this.cartCodeField;
            }
            set {
                this.cartCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CartName {
            get {
                return this.cartNameField;
            }
            set {
                this.cartNameField = value;
            }
        }
        
        /// <remarks/>
        public AST_CartTaskItemDto[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AST_PalletTaskItemDto {
        
        private long aST_PalletTaskItemIdField;
        
        private int fromPalletPositionField;
        
        private string workStationCodeField;
        
        private string materialCodeField;
        
        private string materialNameField;
        
        private string materialBarcodeField;
        
        private int toPickQuantityField;
        
        private bool isSpecialField;
        
        private bool isBigField;
        
        private PickStatus pickStatusField;
        
        private System.Nullable<int> pickedQuantityField;
        
        /// <remarks/>
        public long AST_PalletTaskItemId {
            get {
                return this.aST_PalletTaskItemIdField;
            }
            set {
                this.aST_PalletTaskItemIdField = value;
            }
        }
        
        /// <remarks/>
        public int FromPalletPosition {
            get {
                return this.fromPalletPositionField;
            }
            set {
                this.fromPalletPositionField = value;
            }
        }
        
        /// <remarks/>
        public string WorkStationCode {
            get {
                return this.workStationCodeField;
            }
            set {
                this.workStationCodeField = value;
            }
        }
        
        /// <remarks/>
        public string MaterialCode {
            get {
                return this.materialCodeField;
            }
            set {
                this.materialCodeField = value;
            }
        }
        
        /// <remarks/>
        public string MaterialName {
            get {
                return this.materialNameField;
            }
            set {
                this.materialNameField = value;
            }
        }
        
        /// <remarks/>
        public string MaterialBarcode {
            get {
                return this.materialBarcodeField;
            }
            set {
                this.materialBarcodeField = value;
            }
        }
        
        /// <remarks/>
        public int ToPickQuantity {
            get {
                return this.toPickQuantityField;
            }
            set {
                this.toPickQuantityField = value;
            }
        }
        
        /// <remarks/>
        public bool IsSpecial {
            get {
                return this.isSpecialField;
            }
            set {
                this.isSpecialField = value;
            }
        }
        
        /// <remarks/>
        public bool IsBig {
            get {
                return this.isBigField;
            }
            set {
                this.isBigField = value;
            }
        }
        
        /// <remarks/>
        public PickStatus PickStatus {
            get {
                return this.pickStatusField;
            }
            set {
                this.pickStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> PickedQuantity {
            get {
                return this.pickedQuantityField;
            }
            set {
                this.pickedQuantityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum PickStatus {
        
        /// <remarks/>
        New,
        
        /// <remarks/>
        Picking,
        
        /// <remarks/>
        Finished,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AST_PalletTaskDto {
        
        private long aST_PalletTaskIdField;
        
        private int cFG_PalletIdField;
        
        private string palletCodeField;
        
        private string palletTypeField;
        
        private PalletRotationStatus palletRotationStatusField;
        
        private AST_PalletTaskItemDto[] itemsField;
        
        /// <remarks/>
        public long AST_PalletTaskId {
            get {
                return this.aST_PalletTaskIdField;
            }
            set {
                this.aST_PalletTaskIdField = value;
            }
        }
        
        /// <remarks/>
        public int CFG_PalletId {
            get {
                return this.cFG_PalletIdField;
            }
            set {
                this.cFG_PalletIdField = value;
            }
        }
        
        /// <remarks/>
        public string PalletCode {
            get {
                return this.palletCodeField;
            }
            set {
                this.palletCodeField = value;
            }
        }
        
        /// <remarks/>
        public string PalletType {
            get {
                return this.palletTypeField;
            }
            set {
                this.palletTypeField = value;
            }
        }
        
        /// <remarks/>
        public PalletRotationStatus PalletRotationStatus {
            get {
                return this.palletRotationStatusField;
            }
            set {
                this.palletRotationStatusField = value;
            }
        }
        
        /// <remarks/>
        public AST_PalletTaskItemDto[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum PalletRotationStatus {
        
        /// <remarks/>
        Normal,
        
        /// <remarks/>
        BeginRotation,
        
        /// <remarks/>
        Reversed,
        
        /// <remarks/>
        BeginReverseRotation,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CFG_ChannelCurrentCartDto {
        
        private int cFG_ChannelCurrentCartIdField;
        
        private int cFG_ChannelIdField;
        
        private int positionField;
        
        private System.Nullable<int> cFG_CartIdField;
        
        private string cartCodeField;
        
        private string cartNameField;
        
        /// <remarks/>
        public int CFG_ChannelCurrentCartId {
            get {
                return this.cFG_ChannelCurrentCartIdField;
            }
            set {
                this.cFG_ChannelCurrentCartIdField = value;
            }
        }
        
        /// <remarks/>
        public int CFG_ChannelId {
            get {
                return this.cFG_ChannelIdField;
            }
            set {
                this.cFG_ChannelIdField = value;
            }
        }
        
        /// <remarks/>
        public int Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> CFG_CartId {
            get {
                return this.cFG_CartIdField;
            }
            set {
                this.cFG_CartIdField = value;
            }
        }
        
        /// <remarks/>
        public string CartCode {
            get {
                return this.cartCodeField;
            }
            set {
                this.cartCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CartName {
            get {
                return this.cartNameField;
            }
            set {
                this.cartNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AssortingKanbanCurrentBatchInfo {
        
        private string pickTypeField;
        
        private string projectCodeField;
        
        private string projectStepField;
        
        private string batchCodeField;
        
        private int finishedPalletCountField;
        
        private int totalPalletCountField;
        
        private int finishedMaterialTypeCountField;
        
        private int totalMaterialTypeCountField;
        
        private int finishedMaterialCountField;
        
        private int totalMaterialCountField;
        
        /// <remarks/>
        public string PickType {
            get {
                return this.pickTypeField;
            }
            set {
                this.pickTypeField = value;
            }
        }
        
        /// <remarks/>
        public string ProjectCode {
            get {
                return this.projectCodeField;
            }
            set {
                this.projectCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ProjectStep {
            get {
                return this.projectStepField;
            }
            set {
                this.projectStepField = value;
            }
        }
        
        /// <remarks/>
        public string BatchCode {
            get {
                return this.batchCodeField;
            }
            set {
                this.batchCodeField = value;
            }
        }
        
        /// <remarks/>
        public int FinishedPalletCount {
            get {
                return this.finishedPalletCountField;
            }
            set {
                this.finishedPalletCountField = value;
            }
        }
        
        /// <remarks/>
        public int TotalPalletCount {
            get {
                return this.totalPalletCountField;
            }
            set {
                this.totalPalletCountField = value;
            }
        }
        
        /// <remarks/>
        public int FinishedMaterialTypeCount {
            get {
                return this.finishedMaterialTypeCountField;
            }
            set {
                this.finishedMaterialTypeCountField = value;
            }
        }
        
        /// <remarks/>
        public int TotalMaterialTypeCount {
            get {
                return this.totalMaterialTypeCountField;
            }
            set {
                this.totalMaterialTypeCountField = value;
            }
        }
        
        /// <remarks/>
        public int FinishedMaterialCount {
            get {
                return this.finishedMaterialCountField;
            }
            set {
                this.finishedMaterialCountField = value;
            }
        }
        
        /// <remarks/>
        public int TotalMaterialCount {
            get {
                return this.totalMaterialCountField;
            }
            set {
                this.totalMaterialCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AssortingKanbanTaskInfo {
        
        private AssortingKanbanCurrentBatchInfo currentBatchInfoField;
        
        private CFG_ChannelCurrentCartDto[] currentCartsField;
        
        private AST_PalletTaskDto currentPalletTaskField;
        
        private AST_CartTaskDto currentCartTaskField;
        
        /// <remarks/>
        public AssortingKanbanCurrentBatchInfo CurrentBatchInfo {
            get {
                return this.currentBatchInfoField;
            }
            set {
                this.currentBatchInfoField = value;
            }
        }
        
        /// <remarks/>
        public CFG_ChannelCurrentCartDto[] CurrentCarts {
            get {
                return this.currentCartsField;
            }
            set {
                this.currentCartsField = value;
            }
        }
        
        /// <remarks/>
        public AST_PalletTaskDto CurrentPalletTask {
            get {
                return this.currentPalletTaskField;
            }
            set {
                this.currentPalletTaskField = value;
            }
        }
        
        /// <remarks/>
        public AST_CartTaskDto CurrentCartTask {
            get {
                return this.currentCartTaskField;
            }
            set {
                this.currentCartTaskField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AssortingKanbanTodayStatistics {
        
        private int finishedBatchCountField;
        
        private int totalBatchCountField;
        
        private int finishedPalletCountField;
        
        private int totalPalletCountField;
        
        private int finishedMaterialCountField;
        
        private int totalMaterialCountField;
        
        /// <remarks/>
        public int FinishedBatchCount {
            get {
                return this.finishedBatchCountField;
            }
            set {
                this.finishedBatchCountField = value;
            }
        }
        
        /// <remarks/>
        public int TotalBatchCount {
            get {
                return this.totalBatchCountField;
            }
            set {
                this.totalBatchCountField = value;
            }
        }
        
        /// <remarks/>
        public int FinishedPalletCount {
            get {
                return this.finishedPalletCountField;
            }
            set {
                this.finishedPalletCountField = value;
            }
        }
        
        /// <remarks/>
        public int TotalPalletCount {
            get {
                return this.totalPalletCountField;
            }
            set {
                this.totalPalletCountField = value;
            }
        }
        
        /// <remarks/>
        public int FinishedMaterialCount {
            get {
                return this.finishedMaterialCountField;
            }
            set {
                this.finishedMaterialCountField = value;
            }
        }
        
        /// <remarks/>
        public int TotalMaterialCount {
            get {
                return this.totalMaterialCountField;
            }
            set {
                this.totalMaterialCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void QueryChannelsCompletedEventHandler(object sender, QueryChannelsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryChannelsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryChannelsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CFG_ChannelDto[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CFG_ChannelDto[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void QueryTodayStatisticsCompletedEventHandler(object sender, QueryTodayStatisticsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryTodayStatisticsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryTodayStatisticsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AssortingKanbanTodayStatistics Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AssortingKanbanTodayStatistics)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void QueryCurrentTaskInfoCompletedEventHandler(object sender, QueryCurrentTaskInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryCurrentTaskInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryCurrentTaskInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AssortingKanbanTaskInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AssortingKanbanTaskInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void QueryPDATodayStatisticsCompletedEventHandler(object sender, QueryPDATodayStatisticsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryPDATodayStatisticsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryPDATodayStatisticsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AssortingKanbanTodayStatistics Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AssortingKanbanTodayStatistics)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591