//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace Interfaces.PtlToMes {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ToMesRemoteServiceServiceSoapBinding", Namespace="http://remote.ei.mes.infohow.cn/")]
    public partial class ToMesRemoteServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback syncMaterialExOperationCompleted;
        
        private System.Threading.SendOrPostCallback sendStorageInOutRecordOperationCompleted;
        
        private System.Threading.SendOrPostCallback getVehinfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback assemblyMatResultOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ToMesRemoteServiceService() {
            this.Url = global::Interfaces.Properties.Settings.Default.Interfaces_PtlToMes_ToMesRemoteServiceService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event syncMaterialExCompletedEventHandler syncMaterialExCompleted;
        
        /// <remarks/>
        public event sendStorageInOutRecordCompletedEventHandler sendStorageInOutRecordCompleted;
        
        /// <remarks/>
        public event getVehinfoCompletedEventHandler getVehinfoCompleted;
        
        /// <remarks/>
        public event assemblyMatResultCompletedEventHandler assemblyMatResultCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://remote.ei.mes.infohow.cn/", ResponseNamespace="http://remote.ei.mes.infohow.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string syncMaterialEx([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string reqString) {
            object[] results = this.Invoke("syncMaterialEx", new object[] {
                        reqString});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void syncMaterialExAsync(string reqString) {
            this.syncMaterialExAsync(reqString, null);
        }
        
        /// <remarks/>
        public void syncMaterialExAsync(string reqString, object userState) {
            if ((this.syncMaterialExOperationCompleted == null)) {
                this.syncMaterialExOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsyncMaterialExOperationCompleted);
            }
            this.InvokeAsync("syncMaterialEx", new object[] {
                        reqString}, this.syncMaterialExOperationCompleted, userState);
        }
        
        private void OnsyncMaterialExOperationCompleted(object arg) {
            if ((this.syncMaterialExCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.syncMaterialExCompleted(this, new syncMaterialExCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://remote.ei.mes.infohow.cn/", ResponseNamespace="http://remote.ei.mes.infohow.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sendStorageInOutRecord([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string reqString) {
            object[] results = this.Invoke("sendStorageInOutRecord", new object[] {
                        reqString});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void sendStorageInOutRecordAsync(string reqString) {
            this.sendStorageInOutRecordAsync(reqString, null);
        }
        
        /// <remarks/>
        public void sendStorageInOutRecordAsync(string reqString, object userState) {
            if ((this.sendStorageInOutRecordOperationCompleted == null)) {
                this.sendStorageInOutRecordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendStorageInOutRecordOperationCompleted);
            }
            this.InvokeAsync("sendStorageInOutRecord", new object[] {
                        reqString}, this.sendStorageInOutRecordOperationCompleted, userState);
        }
        
        private void OnsendStorageInOutRecordOperationCompleted(object arg) {
            if ((this.sendStorageInOutRecordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sendStorageInOutRecordCompleted(this, new sendStorageInOutRecordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://remote.ei.mes.infohow.cn/", ResponseNamespace="http://remote.ei.mes.infohow.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getVehinfo([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string reqString) {
            object[] results = this.Invoke("getVehinfo", new object[] {
                        reqString});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getVehinfoAsync(string reqString) {
            this.getVehinfoAsync(reqString, null);
        }
        
        /// <remarks/>
        public void getVehinfoAsync(string reqString, object userState) {
            if ((this.getVehinfoOperationCompleted == null)) {
                this.getVehinfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetVehinfoOperationCompleted);
            }
            this.InvokeAsync("getVehinfo", new object[] {
                        reqString}, this.getVehinfoOperationCompleted, userState);
        }
        
        private void OngetVehinfoOperationCompleted(object arg) {
            if ((this.getVehinfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getVehinfoCompleted(this, new getVehinfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://remote.ei.mes.infohow.cn/", ResponseNamespace="http://remote.ei.mes.infohow.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string assemblyMatResult([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string reqString) {
            object[] results = this.Invoke("assemblyMatResult", new object[] {
                        reqString});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void assemblyMatResultAsync(string reqString) {
            this.assemblyMatResultAsync(reqString, null);
        }
        
        /// <remarks/>
        public void assemblyMatResultAsync(string reqString, object userState) {
            if ((this.assemblyMatResultOperationCompleted == null)) {
                this.assemblyMatResultOperationCompleted = new System.Threading.SendOrPostCallback(this.OnassemblyMatResultOperationCompleted);
            }
            this.InvokeAsync("assemblyMatResult", new object[] {
                        reqString}, this.assemblyMatResultOperationCompleted, userState);
        }
        
        private void OnassemblyMatResultOperationCompleted(object arg) {
            if ((this.assemblyMatResultCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.assemblyMatResultCompleted(this, new assemblyMatResultCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void syncMaterialExCompletedEventHandler(object sender, syncMaterialExCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class syncMaterialExCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal syncMaterialExCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void sendStorageInOutRecordCompletedEventHandler(object sender, sendStorageInOutRecordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sendStorageInOutRecordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sendStorageInOutRecordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void getVehinfoCompletedEventHandler(object sender, getVehinfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getVehinfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getVehinfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void assemblyMatResultCompletedEventHandler(object sender, assemblyMatResultCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class assemblyMatResultCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal assemblyMatResultCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591